name: Execute vr tests

on:
  workflow_run:
    workflows: ["Build pr storybook"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install node_modules
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run build-storybook --quiet

      - name: Serve Storybook and run vr-tests
        id: test
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 8080 --silent" \
            "npx wait-on tcp:127.0.0.1:8080 && npx playwright test tests/vr-tests.spec.ts"
        continue-on-error: true

      - name: Upload test-result
        uses: actions/upload-artifact@v4
        with:
          name: vr-test-${{ github.event.pull_request.number }}
          path: playwright-report

  update-page:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download test-result
        uses: actions/download-artifact@v5
        with:
          name: vr-test-${{ github.event.pull_request.number }}
          path: playwright-report

      - name: Prepare preview directory
        run: |
          mkdir -p docs/pr-${{ github.event.pull_request.number }}/vr-test
          rm -rf docs/pr-${{ github.event.pull_request.number }}/vr-test/*
          cp -r playwright-report/* docs/pr-${{ github.event.pull_request.number }}/vr-test/

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Upload vr-test pr-${{ github.event.pull_request.number }}"
          git push origin gh-pages

      - name: Fail job if tests failed
        if: steps.test.outcome == 'failure'
        run: exit 1
