name: Execute Visual Regression Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - "components/**"

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install node_modules
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run build-storybook --quiet

      - name: Serve Storybook and run vr-tests
        id: test
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 8080 --silent" \
            "npx wait-on tcp:127.0.0.1:8080 && npx playwright test tests/vr-tests.spec.ts"

      - name: Prepare preview directory
        run: |
          mkdir -p src/github-pages/pr-${{ github.event.pull_request.number }}/vr-test
          mkdir -p src/github-pages/pr-${{ github.event.pull_request.number }}/storybook

      - name: Set files to preview directory
        run: |
          cp -r playwright-report/* src/github-pages/pr-${{ github.event.pull_request.number }}/vr-test/
          cp -r storybook-static/* src/github-pages/pr-${{ github.event.pull_request.number }}/storybook/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/github-pages/pr-${{ github.event.pull_request.number }}

      - name: Deployment
        uses: actions/deploy-pages@v4

      - name: Add comment
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo "vr-test: https://boguchi.github.io/components-expansion/vr-test"
            echo "storybook: https://boguchi.github.io/components-expansion/storybook"
          } > /tmp/comment
          gh pr comment "${PR_NUMBER}" -F /tmp/comment --edit-last
